#!/bin/csh

set output = /dev/ttyS1

if ($#argv < 2) then
    echo 'usage loadCode <page> <file>'
    exit
endif

set page = $argv[1]
set filename = $argv[2] 

if ( $page <= '3' && $page >= '0' )  then
else
    echo 'usage loadCode <page> <file>, page is 0..3'
    exit
endif

if ( ! -f $filename ) then
    echo 'file not found,' $filename
    exit
endif

# start independent process listening for serial response;
#  kill it on exit
cat -s - < /dev/ttyS1 &
onintr killcat
nohup

/bin/echo -ne 'NE \r' > $output
sleep 1
/bin/echo -ne 'WF '$page' \r' > $output
sleep 1
cat - < $filename | tr '\n' '\r' > $output
sleep 1
/bin/echo -ne 'OF '$page' \r' > $output

sleep 10

killcat:
kill %1


