#!/bin/csh

echo 'Killing processes...'
killall serial_sender.e >& /dev/null
killall time_sender.e >& /dev/null
killall run.e >& /dev/null
killall key_sender.e >& /dev/null
# remove leftover simpleDaq processes
killall cat >& /dev/null

echo 'Removing message queues...'
ipcs -q | grep '0x' | awk '{print $2}' | xargs -i ipcrm msg {}











