#!/bin/csh

# start independent process listening for serial response;
#  kill it on exit

set serialDevice = /dev/ttyS1
if ( -e ~/.particle-port ) then
  set serialDevice = `cat ~/.particle-port`
endif

cat -s - < $serialDevice &
onintr killcat
nohup

set lastcommand = " "

# note: use $lastcommand:q to bundle all words into one variable, separated
#          by spaces

while ( $lastcommand:q != "quit" )
  set lastcommand = $<:q
  if ( $lastcommand:q != "quit" ) then
    /bin/echo -ne "${lastcommand} \r" > $serialDevice	
  endif
end

killcat:
kill %1
